
 @baseUrl=http://localhost:3030
# @baseUrl=https://surveymonkey-development-ctrns.ondigitalocean.app/api

POST {{baseUrl}}/
Content-Type: application/json

{
        "first_name": "Kalle",
        "last_name": "Anka"
}

###

GET {{baseUrl}}/

###

GET {{baseUrl}}/2

###

PUT {{baseUrl}}/202
Content-Type: application/json

{
      "first_name": "Kalle",
        "last_name": "Anka"
}